---
# Handlers for JVS role

- name: reload systemd
  systemd:
    daemon_reload: true
  listen: reload systemd

- name: reload jvs config
  debug:
    msg: "JVS configuration reloaded"
  listen: reload jvs config

- name: jvs installed
  debug:
    msg: "JVS {{ jvs_version }} installed successfully"
  listen: jvs installed
