apiVersion: jvs.io/v1alpha1
kind: Workspace
metadata:
  name: example-workspace
spec:
  replicas: 1
  storage: 10Gi
  storageClassName: standard
  defaultEngine: copy
  juiceFsConfig:
    source: redis://redis.default.svc.cluster.local:6379/0
  retentionPolicy:
    keepMinSnapshots: 10
    keepMinAge: 24h
  autoSnapshot:
    enabled: true
    schedule: "0 */6 * * *"
    template: checkpoint
    maxSnapshots: 30
