apiVersion: jvs.io/v1alpha1
kind: Snapshot
metadata:
  name: example-snapshot
spec:
  workspace: example-workspace
  note: "Pre-deployment snapshot"
  tags:
  - release
  - pre-deploy
  template: pre-deploy
  compression:
    type: gzip
    level: 6
